import { createSlice } from "@reduxjs/toolkit";

const initalState = {
  users: [],
  reviews: [
    "I recently booked a trip to Miami with this travel company and it was an absolute dream! The staff were incredibly helpful in planning out all the details of my trip and ensuring that everything went smoothly. The accommodations they arranged for me were top-notch and exceeded all of my expectations. I was able to experience all the best parts of Miami thanks to their insider knowledge and recommendations. I would highly recommend this company to anyone looking to plan a trip to Miami. Their attention to detail and customer service is second to none.",
    "I recently had the pleasure of booking a trip with Legends Travel Co out of Miami, Florida and it was truly a fantastic experience. The customer service was top notch and the itinerary was planned to perfection. Every detail was taken care of and the trip exceeded all of my expectations. The flight was on time, the hotel accommodations were luxurious and the tour guides were knowledgeable and personable. I highly recommend Legends Travel Co for all of your travel needs and I will definitely be using their services again in the future.",
    "I had an amazing experience with Legends Travel Co. out of Miami. They planned the perfect vacation for my family, including flights, hotel, and activities. Their customer service was top-notch and they were always available to answer any questions we had. The guides were knowledgeable and made sure we had a great time. We loved the hotel they picked for us, it was in a great location and had all the amenities we needed. I would highly recommend Legends Travel Co. to anyone planning a trip to Miami and we will definitely be using their services again in the future!",
    "I recently booked a trip to Miami Beach through Legends Travel Agency and it was a vacation of a lifetime. The travel agency was able to organize my flight, hotel, and activities seamlessly. The customer service was excellent, they were always available to answer any questions I had and were very responsive. The hotel they booked for me was in a perfect location and had all the amenities I needed. The activities they arranged for me were so much fun and I got to experience the real Miami Beach. I would highly recommend Legends Travel Agency to anyone looking for a hassle-free and enjoyable vacation. I will definitely be using their services again in the future.",
    "Booking my trip to Miami Beach through Legends Travel Agency was a dream come true. The agency was able to handle all the details, from my flight to my hotel and activities. The customer service was top notch, they were always ready to help me with any questions and needs. The hotel was in a prime location, and it was fully equipped with everything I needed. The activities they had planned for me were really fun and I got to explore the real Miami Beach. I highly recommend Legends Travel Agency to anyone looking for a stress-free and enjoyable vacation. I will definitely use their services again in the future.",
    "Booking my trip to Brickell with Legends Travel Agency was a fantastic experience. They took care of everything from my flight to my hotel and activities. Their customer service was excellent, they were always available to assist me with any questions and concerns. The hotel they chose for me was in a great location and had all the amenities I needed. The activities they planned for me were really fun and allowed me to discover the real Brickell. I highly recommend Legends Travel Agency for anyone looking for a hassle-free and enjoyable vacation. I will definitely use their services again in the future.",
    "If you're looking for a hassle-free and enjoyable vacation, look no further than Legends Travel Agency. They took care of all the details for my trip to Brickell, from my flight to my hotel and activities. Their customer service was impeccable, they were always available to answer any questions I had and were very responsive. The hotel they booked for me was in a perfect location and had all the amenities I needed. The activities they arranged for me were so much fun and I got to experience the real Brickell. I highly recommend Legends Travel Agency and I will definitely be using their services again in the future.",
    "For a once in a lifetime experience, I highly recommend booking a trip to the Florida Everglades through Legends Travel Agency. They took care of all the details, from my flight to my hotel and activities. Their customer service was top-notch, they were always ready to help me with any questions and needs. The hotel they chose for me was in a great location, and it was fully equipped with everything I needed. The activities they planned for me were really fun and allowed me to discover the real Florida Everglades. I would highly recommend Legends Travel Agency to anyone looking for a stress-free and enjoyable vacation. I will definitely use their services again in the future.",
    "If you're looking for an adventure of a lifetime, you must book a trip to the Florida Everglades with Legends Travel Agency. From the moment I contacted them, their customer service was outstanding. They planned an itinerary that perfectly matched my interests and budget. The accommodations they booked for me were comfortable and well-located, and the activities they arranged were exciting and well-organized. The tour guides were friendly and knowledgeable, making the whole trip a truly unforgettable experience. I had a chance to explore the beautiful and exotic wildlife, and it was an experience I will never forget. I would highly recommend Legends Travel Agency to anyone who wants to experience the real Florida Everglades and I will definitely be using their services again in the future.",
    "Booking my trip to Little Havana with Legends Travel Agency was one of the best decisions I have made. From the moment I contacted them, their customer service was outstanding. They planned an itinerary that perfectly matched my interests and budget. The accommodations they booked for me were comfortable and well-located, and the activities they arranged were exciting and well-organized. The tour guides were friendly and knowledgeable, making the whole trip a truly unforgettable experience. I had a chance to explore the vibrant culture, delicious food and lively music of Little Havana, and it was an experience I will never forget. I would highly recommend Legends Travel Agency to anyone who wants to experience the real Little Havana and I will definitely be using their services again in the future.",
    "I was looking for an authentic experience of Little Havana, and Legends Travel Agency exceeded my expectations. The planning process was seamless from start to finish, and their customer service was top notch. They arranged for me a perfect itinerary, that included not only the famous landmarks but also the hidden gems of Little Havana. The accommodations were comfortable and well-located, and the activities they arranged were very exciting. The tour guides were friendly and knowledgeable, giving me an in-depth look at the culture, history and lifestyle of Little Havana. I would highly recommend Legends Travel Agency to anyone who wants to experience the real Little Havana, and I will definitely be using their services again in the future.",
    "If you're looking for an off-the-beaten-path experience in Florida, I highly recommend booking a trip to Wynwood with Legends Travel Agency. They took care of all the details, from my flight to my hotel and activities. Their customer service was excellent, they were always ready to help me with any questions and needs. The hotel they chose for me was in a great location, and it was fully equipped with everything I needed. The activities they planned for me were unique and allowed me to discover the real Wynwood, from the street art to the local food scene. I had a chance to explore the vibrant and colorful neighborhood, and it was an experience I will never forget. I would highly recommend Legends Travel Agency to anyone looking for an authentic and unforgettable vacation in Wynwood and I will definitely use their services again in the future.",
    "For an experience unlike any other, I recommend a trip to Wynwood organized by Legends Travel Agency. From start to finish, the level of service and attention to detail was outstanding. They understood my preferences and tailored an itinerary to match, including a stay at a charming boutique hotel and a variety of activities that allowed me to fully immerse in the neighborhood's vibrant culture and art scene. The tour guides were knowledgeable, friendly and always available for any questions. I was able to discover the hidden gems of Wynwood, from the street art to the local food scene. It was truly an unforgettable experience and I will definitely be using Legends Travel Agency again in the future.",
    "For a taste of the vibrant and cosmopolitan side of Miami, look no further than a trip organized by Legends Travel Agency to downtown Miami. From the moment I contacted them, the team went above and beyond to create a bespoke itinerary that catered to my interests and preferences. Their customer service was impeccable and they were always ready to help me with any questions or needs. The accommodations were luxurious and well-located, and the activities they arranged were diverse and exciting, from visiting the famous landmarks to exploring the local food scene. I had a chance to discover the pulse of the city and it was an experience I will never forget. I would highly recommend Legends Travel Agency to anyone looking for a unique and unforgettable vacation in downtown Miami, and I will definitely use their services again in the future."
  ],
};

export const userSlice = createSlice({
  name: "userSlice",
  initialState: initalState,
  reducers: {
    getUsers: (state, action) => {
      state.users = action.payload;
    },
  },
});

export const { getUsers } = userSlice.actions;

export default userSlice.reducer;
